// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ConsultingApp.Models
{
    public partial class Invoice
    {
        [Key]
        public int Invoice_ID { get; set; }
        public int Project_ID { get; set; }
        public DateTime DateIssued { get; set; }
        public int Amount { get; set; }
        public string Status { get; set; }

        public virtual Project Project { get; set; }
    }
}