// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ConsultingApp.Models
{
    public partial class ProjectEmployee
    {
        [Key]
        public int ProjectEmployee_ID { get; set; }
        public int Project_ID { get; set; }
        public int Employee_ID { get; set; }
        public string Role { get; set; }
        public int HoursWorked { get; set; }

        public virtual Employee Employee { get; set; }
        public virtual Project Project { get; set; }
    }
}